# Nginx
FROM nginx:stable-alpine3.17
WORKDIR /app
COPY server/nginx-gw-nossl.conf /etc/nginx/nginx-nossl.conf
COPY server/nginx-gw-ssl.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]