// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package postgres_sqlc

import (
	"context"
)

const getOne = `-- name: GetOne :one
select 1
`

func (q *Queries) GetOne(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getOne)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
