version: '3.7'
networks:
  e_learning_support:
    name: elearning_support_network
    external: true
services:
  fe_next_app:
    container_name: elearning_support_fe_next
    image: leopepe2012/elearning_support_system:fe-next
    privileged: true
    user: root
    restart: always
    environment:
      - "NODE_ENV=production"
      - "TZ=Asia/Ho_Chi_Minh"
    networks:
      - e_learning_support
    ports:
      - "3002:3000"
    expose:
      - 3000