#Cấu hình server
server:
  port: 8088
  servlet:
    context-path: /e-learning/sp
    encoding:
      charset: utf-8
      enabled: true
logging:
  level:
    org.apache.kafka: ERROR

# Cấu hình spring
spring:
  master:
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://45.251.114.59:5465/elearning_support_db
      username: elearning_support_admin
      password: els@admin
      hikari:
        schema: elearning_support_dev
        pool-name: masterDataSourcePool
  slave:
    datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://45.251.114.59:5435/elearning_support_db
      username: elearning_support_admin
      password: els@admin
      hikari:
        schema: elearning_support_dev
        pool-name: slaveDataSourcePool

  # Cấu hình chạy kết nối Mongodb
  data:
    mongodb:
      host: 45.251.114.59
      port: 27017
      database: elearning_support_db
      username: elearning_support_admin
      password: els@admin
      authentication-database: elearning_support_db

  # Database migration
  flyway:
    enabled: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://els_postgres_master:5432/elearning_support_db
    user: elearning_support_admin
    password: els@admin
    schemas: elearning_support_dev
    default-schema: elearning_support_dev
  #Cấu hình Spring Data JPA
  jpa:
    hibernate:
      ddlAuto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comment: true
        format_sql: true
        default_schema: elearning_support_dev
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        #generate_statistics: true
  #Cấu hình servlet : upload multipart file
  servlet:
    multipart:
      enabled: true
      max-file-size: 16MB
      max-request-size: 256MB
      file-size-threshold: 2KB
  #Cấu hình server gửi mail
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: app20222mailsv@gmail.com
    password: jfdzigexvxbhcwoi
    account-password: App20222@mail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  #            Cấu hình nếu sử dụng SSL
  #          socketFactory:
  #            port: 465
  #            class: javax.net.ssl.SSLSocketFactory

  # Cấu hình redis
  redis:
    host: 45.251.114.59
    port: 6381
    connect-timeout: 30000
    username: default
    password: els@redis
    database: 0

  #Cấu hình cache
  cache:
    type: redis
    redis:
      key-prefix: ELS@CACHE-
      time-to-live: 300000 #5 mins

    #  Cấu hình kafka
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092
    consumer:
      group-id: els_consumer_grp_1
      group-instance-id: backend_sp_app_consumer_1
    producer:
      retries: 3 # retry 3 times
      batch-size: 100
      default:
        topic: TopicELearningSupportSystem
      client-id: backend_sp_app
    options:
      enabled: false

  # Cấu hình GraphQl
  graphql:
    path: /api/graphql
    graphiql:
      enabled: true
    websocket:
      path: /api/graphql/socket
    cors:
      allowed-methods: '*'
      allowed-headers: '*'
      allowed-origins: '*'
    schema:
      printer:
        enabled: true

# Cấu hình Json Web Token
jwt:
  secretKey: ELEARNINGKsu295JdkjKHJJHW2349gfbnaf23cheh34HIMAde24
  accessTokenExpiredMs: 100000000
  refreshTokenExpiredMs: 100000000000
  signatureAlgorithm: HS256

# Cấu hình batch async
batch:
  active: false
  async:
    properties:
      common:
        core_thread: 10
        max_thread: 10
        queue_capacity: 500
      clean-up:
        core_thread: 10
        max_thread: 10
        queue_capacity: 100
      db-save:
        core_thread: 10
        max_thread: 10
        queue_capacity: 500

# Cấu hình Server Cloudinary
cloudinary:
  cloud:
    name: app20222-cloudinary
    api-key: 262418987222994
    api-secret: RpT-xRSXwTpwcR9hCyy8CWTLqLs

# Cấu hình file storage
app:
  host: localhost:8088
  file-storage:
    resource-path: /resources/**
    default-stored-type: INTERNAL_SERVER
  mail:
    generate-domain: yopmail.com
    mail-code-prefix: ELS_MAIL_

# Cấu hình firebase
firebase:
  config: elearningsupportsystem-55777-firebase-adminsdk-8oqd8-6bb7d37704.json
  app-name: e-learning_support_system

# host module AI python
python-ai-server:
  api-key: apikeyels2019271820232
  domain: http://127.0.0.1:8089
  apis:
    ai-scoring: /api/scoring